/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author herma
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        northPnl = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        notValidBtn = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        openBtn = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        searchTf = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        searchBtn = new javax.swing.JButton();
        eastPnl = new javax.swing.JPanel();
        southPnl = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        updateBtn = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        statusLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        westPnl = new javax.swing.JPanel();
        centerPnl = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        tableTb = new javax.swing.JTabbedPane();
        userTb = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTbl = new javax.swing.JTable();
        advertismentTb = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        advertismentTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanel1.setBackground(new java.awt.Color(219, 195, 140));
        jPanel1.setLayout(new java.awt.BorderLayout());

        northPnl.setBackground(new java.awt.Color(219, 195, 140));
        northPnl.setPreferredSize(new java.awt.Dimension(678, 50));
        northPnl.setLayout(new java.awt.GridLayout(1, 0));

        jPanel8.setBackground(new java.awt.Color(219, 195, 140));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        deleteBtn.setBackground(new java.awt.Color(242, 229, 187));
        deleteBtn.setText("Törlés");
        deleteBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel8.add(deleteBtn);

        northPnl.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(219, 195, 140));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 15, 10));

        notValidBtn.setBackground(new java.awt.Color(242, 229, 187));
        notValidBtn.setText("Nem valós");
        notValidBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel9.add(notValidBtn);
        notValidBtn.setVisible(false);

        northPnl.add(jPanel9);

        jPanel12.setBackground(new java.awt.Color(219, 195, 140));
        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 0, 10));

        openBtn.setBackground(new java.awt.Color(242, 229, 187));
        openBtn.setText("Megnyit");
        openBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel12.add(openBtn);
        openBtn.setVisible(false);

        northPnl.add(jPanel12);

        jPanel11.setBackground(new java.awt.Color(219, 195, 140));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        northPnl.add(jPanel11);

        jPanel10.setBackground(new java.awt.Color(219, 195, 140));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 10));

        searchTf.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel10.add(searchTf);

        northPnl.add(jPanel10);

        jPanel7.setBackground(new java.awt.Color(219, 195, 140));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 10));

        searchBtn.setBackground(new java.awt.Color(242, 229, 187));
        searchBtn.setText("Keresés");
        searchBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel7.add(searchBtn);

        northPnl.add(jPanel7);

        jPanel1.add(northPnl, java.awt.BorderLayout.PAGE_START);

        eastPnl.setBackground(new java.awt.Color(219, 195, 140));

        javax.swing.GroupLayout eastPnlLayout = new javax.swing.GroupLayout(eastPnl);
        eastPnl.setLayout(eastPnlLayout);
        eastPnlLayout.setHorizontalGroup(
            eastPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        eastPnlLayout.setVerticalGroup(
            eastPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jPanel1.add(eastPnl, java.awt.BorderLayout.LINE_END);

        southPnl.setBackground(new java.awt.Color(219, 195, 140));
        southPnl.setPreferredSize(new java.awt.Dimension(678, 50));
        southPnl.setLayout(new java.awt.GridLayout(1, 3));

        jPanel14.setBackground(new java.awt.Color(219, 195, 140));
        jPanel14.setPreferredSize(new java.awt.Dimension(110, 39));
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 2));

        updateBtn.setBackground(new java.awt.Color(242, 229, 187));
        updateBtn.setText("Frissítés");
        updateBtn.setPreferredSize(new java.awt.Dimension(90, 35));
        jPanel14.add(updateBtn);
        updateBtn.setVisible(false);

        southPnl.add(jPanel14);

        jPanel16.setBackground(new java.awt.Color(219, 195, 140));
        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        statusLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel16.add(statusLbl);

        southPnl.add(jPanel16);

        jPanel2.setBackground(new java.awt.Color(219, 195, 140));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 2));

        exitBtn.setBackground(new java.awt.Color(242, 229, 187));
        exitBtn.setText("Kilépés");
        exitBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel2.add(exitBtn);

        southPnl.add(jPanel2);

        jPanel1.add(southPnl, java.awt.BorderLayout.PAGE_END);

        westPnl.setBackground(new java.awt.Color(219, 195, 140));

        javax.swing.GroupLayout westPnlLayout = new javax.swing.GroupLayout(westPnl);
        westPnl.setLayout(westPnlLayout);
        westPnlLayout.setHorizontalGroup(
            westPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        westPnlLayout.setVerticalGroup(
            westPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jPanel1.add(westPnl, java.awt.BorderLayout.LINE_START);

        centerPnl.setBackground(new java.awt.Color(219, 195, 140));
        centerPnl.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(219, 195, 140));
        jPanel3.setPreferredSize(new java.awt.Dimension(944, 5));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        centerPnl.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel17.setBackground(new java.awt.Color(219, 195, 140));
        jPanel17.setPreferredSize(new java.awt.Dimension(5, 263));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        centerPnl.add(jPanel17, java.awt.BorderLayout.LINE_END);

        jPanel18.setBackground(new java.awt.Color(219, 195, 140));
        jPanel18.setPreferredSize(new java.awt.Dimension(944, 5));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        centerPnl.add(jPanel18, java.awt.BorderLayout.PAGE_END);

        jPanel19.setBackground(new java.awt.Color(219, 195, 140));
        jPanel19.setPreferredSize(new java.awt.Dimension(5, 358));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        centerPnl.add(jPanel19, java.awt.BorderLayout.LINE_START);

        jPanel20.setBackground(new java.awt.Color(219, 195, 140));
        jPanel20.setLayout(new java.awt.GridLayout(1, 0));

        tableTb.setBackground(new java.awt.Color(242, 229, 187));

        userTb.setLayout(new java.awt.GridLayout(1, 1));

        userTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(userTbl);

        userTb.add(jScrollPane1);

        tableTb.addTab("Felhasználók", userTb);

        advertismentTb.setLayout(new java.awt.GridLayout(1, 1));

        advertismentTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(advertismentTbl);

        advertismentTb.add(jScrollPane2);

        tableTb.addTab("Jelentett hirdetések", advertismentTb);

        jPanel20.add(tableTb);

        centerPnl.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel1.add(centerPnl, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel advertismentTb;
    private javax.swing.JTable advertismentTbl;
    private javax.swing.JPanel centerPnl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JPanel eastPnl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel northPnl;
    private javax.swing.JButton notValidBtn;
    private javax.swing.JButton openBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTf;
    private javax.swing.JPanel southPnl;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JTabbedPane tableTb;
    private javax.swing.JButton updateBtn;
    private javax.swing.JPanel userTb;
    private javax.swing.JTable userTbl;
    private javax.swing.JPanel westPnl;
    // End of variables declaration//GEN-END:variables
    public JButton getDeleteBtn() {
        return deleteBtn;
    }
    public JButton getExitBtn() {
        return exitBtn;
    }
    public JButton getSearchBtn() {
        return searchBtn;
    }
    public JButton getNotValidBtn() {
        return notValidBtn;
    }
    public JButton getUpdateBtn() {
        return updateBtn;
    }
    public JButton getOpenBtn() {
        return openBtn;
    }
    public JTextField getSearchTf() {
        return searchTf;
    }
    public void setStatusLbl(String text) {
        statusLbl.setText(text);
    }
    public JTabbedPane getTableTb() {
        return tableTb;
    }
    public JTable getUserTbl() {
        return userTbl;
    }
    public JTable getAdvertismentTbl() {
        return advertismentTbl;
    }
}
